version: '3.8'

services:
  outlook-mcp-server:
    build: .
    container_name: outlook-mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CLIENT_ID=your-client-id
      - SESSION_SECRET=your-session-secret
      - REDIRECT_URI=http://localhost:3000/auth/callback
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # Uncomment if using a Redis session store in production
    # depends_on:
    #   - redis
  
  # Uncomment for production use with Redis session store
  # redis:
  #   image: redis:alpine
  #   container_name: outlook-mcp-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

# Uncomment for production use with Redis session store
# volumes:
#   redis-data:
